#! /bin/bash
# display the git branch in terminal

branch="`git branch 2>/dev/null | grep "^\*" | sed -e "s/^\*\ //"`"
if [ "${branch}" != "" ];then
if [ "${branch}" = "(no branch)" ];then
   branch="(`git rev-parse --short HEAD`...)"
fi
echo " [$branch]"
fi
